/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Logged in */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Me"];
                    };
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update profile (displayName only in v1) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MePatch"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Me"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create account; sets session cookie */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Me"];
                    };
                };
                400: components["responses"]["BadRequest"];
                /** @description Email or username already in use */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in; sets session cookie */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Me"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log out; clears session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No content; clears gd_session cookie */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{username}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public profile (no email) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    username: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserPublic"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List assets (cursor pagination) */
        get: {
            parameters: {
                query: {
                    /** @description public = explore; private = my library */
                    scope: "public" | "private";
                    cursor?: string | null;
                    limit?: number;
                    sort?: "createdAt_desc" | "createdAt_asc" | "updatedAt_desc";
                    /** @description Set to `no` to return only assets that have no `asset_images` rows (image-less). Omit to list all. */
                    img?: "no";
                    /** @description Only with `scope=public`. Filter to public assets whose author matches this username. Returns 400 if used with `scope=private`. */
                    authorUsername?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Page of assets */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedAssets"];
                    };
                };
            };
        };
        put?: never;
        /** Create asset (private by default) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AssetCreate"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Asset"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get asset by id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["AssetId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Asset"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /** Soft-delete a private asset (owner only); public assets rejected */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["AssetId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Asset marked deleted (ghost); removed from library lists */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Public or invalid state */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        /** Update editable fields (private assets only; public = read-only) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["AssetId"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AssetUpdate"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Asset"];
                    };
                };
                /** @description Public asset — content frozen after publish */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/assets/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish private asset to public (irreversible content freeze per product rules) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["AssetId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Asset"];
                    };
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{id}/fork": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fork asset into current user's private library */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["AssetId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Asset"];
                    };
                };
                /** @description Source missing or not forkable */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{id}/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request image generation for private asset only (public = read-only) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["AssetId"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        extraPrompt?: string | null;
                    };
                };
            };
            responses: {
                /** @description Job accepted; new AssetImage pending */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AssetImage"];
                    };
                };
                /** @description Public asset — no new images after publish */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{id}/images/{imageId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove one image from a private asset (public = read-only; cover_id cleared if needed) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["AssetId"];
                    imageId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Image removed */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{id}/forks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lazy fork neighbourhood (v1 depth=1 only) */
        get: {
            parameters: {
                query: {
                    direction: "upstream" | "downstream";
                    depth?: number;
                };
                header?: never;
                path: {
                    id: components["parameters"]["AssetId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ForkPage"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{id}/fork-graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bounded fork subgraph for graph view (focus asset must be readable like GET /assets/{id}) */
        get: {
            parameters: {
                query?: {
                    maxUpstream?: number;
                    downstreamDepth?: number;
                    maxNodes?: number;
                    /** @description If set, return direct children of this asset only (lazy expand); focus id in path is still the page focus for cache keys */
                    expandFrom?: string;
                    /** @description Max children returned per expandFrom request */
                    childLimit?: number;
                };
                header?: never;
                path: {
                    id: components["parameters"]["AssetId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ForkGraph"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List AI material sessions */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SessionSummary"][];
                    };
                };
            };
        };
        put?: never;
        /** Create session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        title?: string;
                        /** @description optional session staging group to attach */
                        stagingGroupId?: string;
                    };
                };
            };
            responses: {
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SessionDetail"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session-staging-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List session staging groups (independent vs shared draft pool) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SessionStagingGroup"][];
                    };
                };
            };
        };
        put?: never;
        /** Create session staging group */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        name: string;
                        /**
                         * @default independent
                         * @enum {string}
                         */
                        draftStaging?: "independent" | "shared";
                    };
                };
            };
            responses: {
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SessionStagingGroup"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session-staging-groups/{groupId}/drafts": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
            };
            cookie?: never;
        };
        /** List all staging draft rows for this group (shared pool or union of per-session rows) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    groupId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DraftAsset"][];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session-staging-groups/{groupId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete group (sessions unlinked; group-scoped drafts removed) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    groupId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        /** Update name or draft staging mode (mode change requires empty staging in conflict paths) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    groupId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        name?: string;
                        /** @enum {string} */
                        draftStaging?: "independent" | "shared";
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SessionStagingGroup"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sessionId: components["parameters"]["SessionId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SessionDetail"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sessionId: components["parameters"]["SessionId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Archived / deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        /** Update title and/or assign session to a staging group */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sessionId: components["parameters"]["SessionId"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        title?: string;
                        /** @description set null to remove from group */
                        stagingGroupId?: string | null;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SessionDetail"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/sessions/{sessionId}/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start assistant reply stream (SSE, JSONL body lines) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sessionId: components["parameters"]["SessionId"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            responses: {
                /** @description text/event-stream of JSONL lines */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{sessionId}/drafts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a user-authored draft (name + description) to session staging; not auto-created by chat stream */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sessionId: components["parameters"]["SessionId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                        description: string;
                    };
                };
            };
            responses: {
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DraftAsset"];
                    };
                };
                400: components["responses"]["BadRequest"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{sessionId}/drafts/{tempId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a draft from session staging */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sessionId: components["parameters"]["SessionId"];
                    tempId: components["parameters"]["DraftTempId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Removed */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        /** Update a staged draft (name + description) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sessionId: components["parameters"]["SessionId"];
                    tempId: components["parameters"]["DraftTempId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                        description: string;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DraftAsset"];
                    };
                };
                400: components["responses"]["BadRequest"];
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/sessions/{sessionId}/drafts/{tempId}/export-to-library": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Export one staged draft to private library and remove it from staging (atomic)
         * @description Uses draft name/description from the staging row. For shared group staging, `sessionId` must be any chat session in that group (same as PATCH/DELETE draft).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sessionId: components["parameters"]["SessionId"];
                    tempId: components["parameters"]["DraftTempId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Created private asset; draft row deleted */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Asset"];
                    };
                };
                400: components["responses"]["BadRequest"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List projects */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectSummary"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        name: string;
                    };
                };
            };
            responses: {
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectDetail"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: components["parameters"]["ProjectId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectDetail"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: components["parameters"]["ProjectId"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ProjectPatch"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectDetail"];
                    };
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorBody: {
            /** @description Human-readable message for UI */
            error: string;
            /** @description Stable machine code */
            code?: string;
        };
        Me: {
            id: string;
            username: string;
            displayName?: string | null;
        };
        MePatch: {
            displayName?: string | null;
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
            username: string;
            displayName?: string | null;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        UserPublic: {
            id: string;
            username: string;
            displayName?: string | null;
        };
        /** @enum {string} */
        AssetVisibility: "private" | "public" | "deleted";
        AssetImage: {
            id: string;
            assetId: string;
            /** @description CDN template, append ?w= */
            url: string;
            extraPrompt?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** @enum {string} */
            generationStatus: "pending" | "done" | "failed";
        };
        Asset: components["schemas"]["AssetFull"] | components["schemas"]["AssetDeletedGhost"];
        AssetFull: {
            id: string;
            name: string;
            description: string;
            annotation?: string | null;
            authorId: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            visibility: "private" | "public";
            forkedFromId: string | null;
            forkCount: number;
            images: components["schemas"]["AssetImage"][];
            coverImageId: string | null;
            /** Format: date-time */
            deletedAt: string | null;
            author: components["schemas"]["UserPublic"];
        };
        /** @description When visibility=deleted, only these fields are returned */
        AssetDeletedGhost: {
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            visibility: "deleted";
            forkedFromId: string | null;
            /** Format: date-time */
            deletedAt: string | null;
        };
        AssetCreate: {
            name: string;
            description: string;
            annotation?: string | null;
            /** @description optional link to originating AI session */
            sessionId?: string;
            forkedFromId?: string | null;
        };
        AssetUpdate: {
            name?: string;
            description?: string;
            annotation?: string | null;
            coverImageId?: string | null;
        };
        PaginatedAssets: {
            items: components["schemas"]["Asset"][];
            nextCursor: string | null;
            total?: number | null;
        };
        ForkNode: {
            id: string;
            /** @description empty when ghost upstream */
            name?: string;
            visibility: components["schemas"]["AssetVisibility"];
            forkedFromId: string | null;
            /** Format: date-time */
            deletedAt: string | null;
        };
        ForkPage: {
            /** @enum {string} */
            direction: "upstream" | "downstream";
            nodes: components["schemas"]["ForkNode"][];
        };
        ForkGraphNode: components["schemas"]["ForkNode"] & {
            /** @description direct fork children count in DB; 0 when node is hidden stub */
            forkCount: number;
            /** @description Cover image URL if visible; null for deleted/hidden or no image */
            coverImageUrl: string | null;
        };
        ForkGraph: {
            focusAssetId: string;
            nodes: components["schemas"]["ForkGraphNode"][];
            /** @description true if maxNodes or childLimit cut off results */
            truncated: boolean;
        };
        /** @description Staging group attached to a chat session (independent = per-session drafts, shared = one pool per group) */
        SessionStagingGroupRef: {
            id: string;
            name: string;
            /** @enum {string} */
            draftStaging: "independent" | "shared";
        };
        SessionStagingGroup: {
            id: string;
            name: string;
            position: number;
            /** @enum {string} */
            draftStaging: "independent" | "shared";
            /** Format: date-time */
            createdAt: string;
        };
        SessionSummary: {
            id: string;
            title: string;
            /** Format: date-time */
            updatedAt: string;
            draftAssetCount: number;
            stagingGroup?: components["schemas"]["SessionStagingGroupRef"];
        };
        SessionDetail: components["schemas"]["SessionSummary"] & {
            messages?: components["schemas"]["ChatMessage"][];
            draftAssets?: components["schemas"]["DraftAsset"][];
        };
        ChatMessage: {
            id: string;
            /** @enum {string} */
            role: "user" | "assistant" | "system";
            content: string;
            /** Format: date-time */
            createdAt: string;
        };
        DraftAsset: {
            tempId: string;
            name: string;
            description: string;
            /** @default false */
            done: boolean;
            /** @description Present when draftStaging is independent — session that owns this row (for PATCH/DELETE paths) */
            ownerSessionId?: string;
            ownerSessionTitle?: string;
        };
        ProjectSummary: {
            id: string;
            name: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ProjectDetail: components["schemas"]["ProjectSummary"] & {
            /** @description tldraw document JSON; only asset refs are semantic */
            canvasDocument?: {
                [key: string]: unknown;
            };
        };
        ProjectPatch: {
            name?: string;
            canvasDocument?: {
                [key: string]: unknown;
            };
        };
    };
    responses: {
        /** @description Bad request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorBody"];
            };
        };
        /** @description Unauthorized */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorBody"];
            };
        };
        /** @description Forbidden */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorBody"];
            };
        };
        /** @description Not found (or 404 for private resource per product rules) */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorBody"];
            };
        };
    };
    parameters: {
        AssetId: string;
        SessionId: string;
        DraftTempId: string;
        ProjectId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
