// Package oapigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package oapigen

import (
	"encoding/json"
	"errors"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for AssetImageGenerationStatus.
const (
	Done    AssetImageGenerationStatus = "done"
	Failed  AssetImageGenerationStatus = "failed"
	Pending AssetImageGenerationStatus = "pending"
)

// Valid indicates whether the value is a known member of the AssetImageGenerationStatus enum.
func (e AssetImageGenerationStatus) Valid() bool {
	switch e {
	case Done:
		return true
	case Failed:
		return true
	case Pending:
		return true
	default:
		return false
	}
}

// Defines values for AssetVisibility.
const (
	AssetVisibilityDeleted AssetVisibility = "deleted"
	AssetVisibilityPrivate AssetVisibility = "private"
	AssetVisibilityPublic  AssetVisibility = "public"
)

// Valid indicates whether the value is a known member of the AssetVisibility enum.
func (e AssetVisibility) Valid() bool {
	switch e {
	case AssetVisibilityDeleted:
		return true
	case AssetVisibilityPrivate:
		return true
	case AssetVisibilityPublic:
		return true
	default:
		return false
	}
}

// Defines values for ChatMessageRole.
const (
	Assistant ChatMessageRole = "assistant"
	System    ChatMessageRole = "system"
	User      ChatMessageRole = "user"
)

// Valid indicates whether the value is a known member of the ChatMessageRole enum.
func (e ChatMessageRole) Valid() bool {
	switch e {
	case Assistant:
		return true
	case System:
		return true
	case User:
		return true
	default:
		return false
	}
}

// Defines values for ForkPageDirection.
const (
	ForkPageDirectionDownstream ForkPageDirection = "downstream"
	ForkPageDirectionUpstream   ForkPageDirection = "upstream"
)

// Valid indicates whether the value is a known member of the ForkPageDirection enum.
func (e ForkPageDirection) Valid() bool {
	switch e {
	case ForkPageDirectionDownstream:
		return true
	case ForkPageDirectionUpstream:
		return true
	default:
		return false
	}
}

// Defines values for GetAssetsParamsScope.
const (
	GetAssetsParamsScopePrivate GetAssetsParamsScope = "private"
	GetAssetsParamsScopePublic  GetAssetsParamsScope = "public"
)

// Valid indicates whether the value is a known member of the GetAssetsParamsScope enum.
func (e GetAssetsParamsScope) Valid() bool {
	switch e {
	case GetAssetsParamsScopePrivate:
		return true
	case GetAssetsParamsScopePublic:
		return true
	default:
		return false
	}
}

// Defines values for GetAssetsParamsSort.
const (
	CreatedAtAsc  GetAssetsParamsSort = "createdAt_asc"
	CreatedAtDesc GetAssetsParamsSort = "createdAt_desc"
	UpdatedAtDesc GetAssetsParamsSort = "updatedAt_desc"
)

// Valid indicates whether the value is a known member of the GetAssetsParamsSort enum.
func (e GetAssetsParamsSort) Valid() bool {
	switch e {
	case CreatedAtAsc:
		return true
	case CreatedAtDesc:
		return true
	case UpdatedAtDesc:
		return true
	default:
		return false
	}
}

// Defines values for GetAssetsIdForksParamsDirection.
const (
	GetAssetsIdForksParamsDirectionDownstream GetAssetsIdForksParamsDirection = "downstream"
	GetAssetsIdForksParamsDirectionUpstream   GetAssetsIdForksParamsDirection = "upstream"
)

// Valid indicates whether the value is a known member of the GetAssetsIdForksParamsDirection enum.
func (e GetAssetsIdForksParamsDirection) Valid() bool {
	switch e {
	case GetAssetsIdForksParamsDirectionDownstream:
		return true
	case GetAssetsIdForksParamsDirectionUpstream:
		return true
	default:
		return false
	}
}

// Asset defines model for Asset.
type Asset struct {
	union json.RawMessage
}

// AssetCreate defines model for AssetCreate.
type AssetCreate struct {
	Annotation   *string `json:"annotation,omitempty"`
	Description  string  `json:"description"`
	ForkedFromId *string `json:"forkedFromId,omitempty"`
	Name         string  `json:"name"`

	// SessionId optional link to originating AI session
	SessionId *string `json:"sessionId,omitempty"`
}

// AssetDeletedGhost When visibility=deleted, only these fields are returned
type AssetDeletedGhost struct {
	DeletedAt    *time.Time  `json:"deletedAt"`
	ForkedFromId *string     `json:"forkedFromId"`
	Id           string      `json:"id"`
	Visibility   interface{} `json:"visibility"`
}

// AssetFull defines model for AssetFull.
type AssetFull struct {
	Annotation   *string         `json:"annotation,omitempty"`
	AuthorId     string          `json:"authorId"`
	CoverImageId *string         `json:"coverImageId"`
	CreatedAt    time.Time       `json:"createdAt"`
	DeletedAt    *time.Time      `json:"deletedAt"`
	Description  string          `json:"description"`
	ForkCount    float32         `json:"forkCount"`
	ForkedFromId *string         `json:"forkedFromId"`
	Id           string          `json:"id"`
	Images       []AssetImage    `json:"images"`
	Name         string          `json:"name"`
	UpdatedAt    time.Time       `json:"updatedAt"`
	Visibility   AssetVisibility `json:"visibility"`
}

// AssetImage defines model for AssetImage.
type AssetImage struct {
	AssetId          string                     `json:"assetId"`
	CreatedAt        time.Time                  `json:"createdAt"`
	ExtraPrompt      *string                    `json:"extraPrompt,omitempty"`
	GenerationStatus AssetImageGenerationStatus `json:"generationStatus"`
	Id               string                     `json:"id"`

	// Url CDN template, append ?w=
	Url string `json:"url"`
}

// AssetImageGenerationStatus defines model for AssetImage.GenerationStatus.
type AssetImageGenerationStatus string

// AssetUpdate defines model for AssetUpdate.
type AssetUpdate struct {
	Annotation   *string `json:"annotation,omitempty"`
	CoverImageId *string `json:"coverImageId,omitempty"`
	Description  *string `json:"description,omitempty"`
	Name         *string `json:"name,omitempty"`
}

// AssetVisibility defines model for AssetVisibility.
type AssetVisibility string

// ChatMessage defines model for ChatMessage.
type ChatMessage struct {
	Content   string          `json:"content"`
	CreatedAt time.Time       `json:"createdAt"`
	Id        string          `json:"id"`
	Role      ChatMessageRole `json:"role"`
}

// ChatMessageRole defines model for ChatMessage.Role.
type ChatMessageRole string

// DraftAsset defines model for DraftAsset.
type DraftAsset struct {
	Description string `json:"description"`
	Done        bool   `json:"done"`
	Name        string `json:"name"`
	TempId      string `json:"tempId"`
}

// ErrorBody defines model for ErrorBody.
type ErrorBody struct {
	// Code Stable machine code
	Code *string `json:"code,omitempty"`

	// Error Human-readable message for UI
	Error string `json:"error"`
}

// ForkNode defines model for ForkNode.
type ForkNode struct {
	DeletedAt    *time.Time `json:"deletedAt"`
	ForkedFromId *string    `json:"forkedFromId"`
	Id           string     `json:"id"`

	// Name empty when ghost upstream
	Name       *string         `json:"name,omitempty"`
	Visibility AssetVisibility `json:"visibility"`
}

// ForkPage defines model for ForkPage.
type ForkPage struct {
	Direction ForkPageDirection `json:"direction"`
	Nodes     []ForkNode        `json:"nodes"`
}

// ForkPageDirection defines model for ForkPage.Direction.
type ForkPageDirection string

// Me defines model for Me.
type Me struct {
	DisplayName *string `json:"displayName,omitempty"`
	Id          string  `json:"id"`
	Username    string  `json:"username"`
}

// PaginatedAssets defines model for PaginatedAssets.
type PaginatedAssets struct {
	Items      []Asset  `json:"items"`
	NextCursor *string  `json:"nextCursor"`
	Total      *float32 `json:"total,omitempty"`
}

// ProjectDetail defines model for ProjectDetail.
type ProjectDetail struct {
	// CanvasDocument tldraw document JSON; only asset refs are semantic
	CanvasDocument *map[string]interface{} `json:"canvasDocument,omitempty"`
	Id             string                  `json:"id"`
	Name           string                  `json:"name"`
	UpdatedAt      time.Time               `json:"updatedAt"`
}

// ProjectPatch defines model for ProjectPatch.
type ProjectPatch struct {
	CanvasDocument *map[string]interface{} `json:"canvasDocument,omitempty"`
	Name           *string                 `json:"name,omitempty"`
}

// ProjectSummary defines model for ProjectSummary.
type ProjectSummary struct {
	Id        string    `json:"id"`
	Name      string    `json:"name"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// SessionDetail defines model for SessionDetail.
type SessionDetail struct {
	DraftAssetCount int            `json:"draftAssetCount"`
	DraftAssets     *[]DraftAsset  `json:"draftAssets,omitempty"`
	Id              string         `json:"id"`
	Messages        *[]ChatMessage `json:"messages,omitempty"`
	Title           string         `json:"title"`
	UpdatedAt       time.Time      `json:"updatedAt"`
}

// SessionSummary defines model for SessionSummary.
type SessionSummary struct {
	DraftAssetCount int       `json:"draftAssetCount"`
	Id              string    `json:"id"`
	Title           string    `json:"title"`
	UpdatedAt       time.Time `json:"updatedAt"`
}

// AssetId defines model for AssetId.
type AssetId = string

// ProjectId defines model for ProjectId.
type ProjectId = string

// SessionId defines model for SessionId.
type SessionId = string

// Forbidden defines model for Forbidden.
type Forbidden = ErrorBody

// NotFound defines model for NotFound.
type NotFound = ErrorBody

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorBody

// GetAssetsParams defines parameters for GetAssets.
type GetAssetsParams struct {
	// Scope public = explore; private = my library
	Scope  GetAssetsParamsScope `form:"scope" json:"scope"`
	Cursor *string              `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *int                 `form:"limit,omitempty" json:"limit,omitempty"`
	Sort   *GetAssetsParamsSort `form:"sort,omitempty" json:"sort,omitempty"`
}

// GetAssetsParamsScope defines parameters for GetAssets.
type GetAssetsParamsScope string

// GetAssetsParamsSort defines parameters for GetAssets.
type GetAssetsParamsSort string

// GetAssetsIdForksParams defines parameters for GetAssetsIdForks.
type GetAssetsIdForksParams struct {
	Direction GetAssetsIdForksParamsDirection `form:"direction" json:"direction"`
	Depth     *int                            `form:"depth,omitempty" json:"depth,omitempty"`
}

// GetAssetsIdForksParamsDirection defines parameters for GetAssetsIdForks.
type GetAssetsIdForksParamsDirection string

// PostAssetsIdImagesJSONBody defines parameters for PostAssetsIdImages.
type PostAssetsIdImagesJSONBody struct {
	ExtraPrompt *string `json:"extraPrompt,omitempty"`
}

// PostProjectsJSONBody defines parameters for PostProjects.
type PostProjectsJSONBody struct {
	Name string `json:"name"`
}

// PostSessionsJSONBody defines parameters for PostSessions.
type PostSessionsJSONBody struct {
	Title *string `json:"title,omitempty"`
}

// PostSessionsSessionIdChatJSONBody defines parameters for PostSessionsSessionIdChat.
type PostSessionsSessionIdChatJSONBody struct {
	Message string `json:"message"`
}

// PostAssetsJSONRequestBody defines body for PostAssets for application/json ContentType.
type PostAssetsJSONRequestBody = AssetCreate

// PatchAssetsIdJSONRequestBody defines body for PatchAssetsId for application/json ContentType.
type PatchAssetsIdJSONRequestBody = AssetUpdate

// PostAssetsIdImagesJSONRequestBody defines body for PostAssetsIdImages for application/json ContentType.
type PostAssetsIdImagesJSONRequestBody PostAssetsIdImagesJSONBody

// PostProjectsJSONRequestBody defines body for PostProjects for application/json ContentType.
type PostProjectsJSONRequestBody PostProjectsJSONBody

// PatchProjectsProjectIdJSONRequestBody defines body for PatchProjectsProjectId for application/json ContentType.
type PatchProjectsProjectIdJSONRequestBody = ProjectPatch

// PostSessionsJSONRequestBody defines body for PostSessions for application/json ContentType.
type PostSessionsJSONRequestBody PostSessionsJSONBody

// PostSessionsSessionIdChatJSONRequestBody defines body for PostSessionsSessionIdChat for application/json ContentType.
type PostSessionsSessionIdChatJSONRequestBody PostSessionsSessionIdChatJSONBody

// AsAssetFull returns the union data inside the Asset as a AssetFull
func (t Asset) AsAssetFull() (AssetFull, error) {
	var body AssetFull
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAssetFull overwrites any union data inside the Asset as the provided AssetFull
func (t *Asset) FromAssetFull(v AssetFull) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAssetFull performs a merge with any union data inside the Asset, using the provided AssetFull
func (t *Asset) MergeAssetFull(v AssetFull) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAssetDeletedGhost returns the union data inside the Asset as a AssetDeletedGhost
func (t Asset) AsAssetDeletedGhost() (AssetDeletedGhost, error) {
	var body AssetDeletedGhost
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAssetDeletedGhost overwrites any union data inside the Asset as the provided AssetDeletedGhost
func (t *Asset) FromAssetDeletedGhost(v AssetDeletedGhost) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAssetDeletedGhost performs a merge with any union data inside the Asset, using the provided AssetDeletedGhost
func (t *Asset) MergeAssetDeletedGhost(v AssetDeletedGhost) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Asset) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"visibility"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t Asset) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "deleted":
		return t.AsAssetDeletedGhost()
	case "private":
		return t.AsAssetFull()
	case "public":
		return t.AsAssetFull()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t Asset) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Asset) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
